version: '3'
services:
  api:
    build: ./src/api
    volumes:
      - ./src/api:/app
    ports:
      - 8000:8000
    environment:
      - API_KEY=MY_API_KEY
      - KAFKA_BROKER=kafka:9092
    restart: unless-stopped

  risk_engine:
    build: ./src/risk_engine
    volumes:
      - ./src/risk_engine:/app
    environment:
      - KAFKA_BROKER=kafka:9092
    restart: unless-stopped

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: unless-stopped

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    restart: unless-stopped
